cp params_LP_arbitrary.txt params_LobsDICE_cvxpy_arbitrary.txt
cp params_LP_arbitrary.txt params_SMODICE_KL_cvxpy_arbitrary.txt
cp params_LP_arbitrary.txt params_SMODICE_chi_cvxpy_arbitrary.txt
cp params_LP_arbitrary.txt params_ours_convex_solver_arbitrary.txt